# - name: Configure root access for user ubuntu
#   hosts: masters
#   remote_user: ubuntu
#   become: yes
#   roles:
#     - users

# - name: Install prerequisites
#   hosts: masters
#   remote_user: ubuntu
#   become: yes
#   roles:
#     - 02-install-prerequisites

# - name: install docker
#   hosts: masters
#   remote_user: ubuntu
#   become: yes
#   roles:
#     - 03-install-docker

# - name: take down utility stack
#   hosts: masters
#   remote_user: ubuntu
#   become: yes
#   roles:
#     - 04-take-it-down(us)

# - name: deploy utility stack
#   hosts: masters
#   remote_user: ubuntu
#   become: yes
#   roles:
#     - 05-deploy-utility-stack

- name: Get jenkins credentials
  hosts: masters
  remote_user: ubuntu
  become: yes
  roles:
    - 06-get-jenkins-creds

