- name: Check that the somefile.conf exists
  stat:
    path: workspace/deployment/docker-compose.yml
  register: stat_result

- name: Install, configure, and start Apache
  block:
        - name: take down utility stack
          docker_compose:
            project_src: workspace//utilityStack-deployment
            state: absent

        - name: Delete content & directory of workspace
          file:
            state: absent
            path: workspace//utilityStack-deployment
  when: stat_result.stat.exists!="false"
  ignore_errors: yes